#!/bin/bash

echo "Creating .env file from Vercel Environment Variables..."
cat << EOF > .env
FIREBASE_API_KEY=$FIREBASE_API_KEY
FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
FIREBASE_APP_ID_WEB=$FIREBASE_APP_ID_WEB
FIREBASE_APP_ID_ANDROID=$FIREBASE_APP_ID_ANDROID
FIREBASE_APP_ID_IOS=$FIREBASE_APP_ID_IOS
FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID
FIREBASE_IOS_BUNDLE_ID=$FIREBASE_IOS_BUNDLE_ID
EOF

echo "Installing Flutter..."
git clone https://github.com/flutter/flutter.git -b stable --depth 1
export PATH="$PATH:`pwd`/flutter/bin"

echo "Building Flutter Web..."
flutter build web --release
