name: Build Android App Bundle

on:
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  build:
    name: Build .aab
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.22.x' # Use appropriate flutter version, or leave empty for latest

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Android App Bundle
        run: flutter build appbundle

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 7
